# Generated by Django 3.2.3 on 2021-05-20 15:01

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='accounts/profile/default.jpg', upload_to='accounts/profile/%Y/%m/')),
                ('nationality', django_countries.fields.CountryField(default='KE', max_length=2)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='m', max_length=2, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('is_active', models.BooleanField(default=False, help_text='Activated, users profile is published', verbose_name='Active')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='username')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(help_text='User will be able to login using email', max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=100, null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Used for super user authentications')),
                ('is_superuser', models.BooleanField(default=False, help_text='Means user is admin')),
                ('is_applicant', models.BooleanField(default=False, help_text="Means user can login to applicant's portal")),
                ('is_active', models.BooleanField(default=True, help_text='Means user can login to the system')),
                ('is_archived', models.BooleanField(default=False, help_text='Means User cannot login')),
                ('is_verified', models.BooleanField(default=False, help_text='Means email is verified')),
                ('updated', models.DateTimeField(auto_now=True, help_text='means last time table instance was edited', null=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='time table instance was created', null=True, verbose_name='Created')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
