# Generated by Django 3.2.3 on 2021-05-20 15:01

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.customuser')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
            },
            bases=('account.customuser',),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('instructions', models.TextField(help_text='job instruction')),
                ('sample', models.FileField(default='applicant/sample.pdf', help_text='job sample', upload_to='applicant/%Y/%M')),
                ('sheet', models.URLField(help_text='Job output sheet (google sheet)')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'MTO Job details',
                'verbose_name_plural': 'MTO Job details',
            },
        ),
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Activated, means job will be published', verbose_name='Active')),
                ('is_archived', models.BooleanField(default=False, help_text='Archived, means job will be Unpublished', verbose_name='Archive')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.job')),
            ],
            options={
                'verbose_name': 'MAL Requirements',
                'verbose_name_plural': 'MAL Requirements',
            },
        ),
        migrations.CreateModel(
            name='JobAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Outsource Email Id', max_length=254)),
                ('name', models.CharField(help_text='Outsource Name', max_length=200)),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('job', models.ForeignKey(help_text='Job id', on_delete=django.db.models.deletion.CASCADE, to='applicant.postjob')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='subject')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(help_text='Feedback sent by applicant to admin')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.profile')),
                ('title', models.CharField(choices=[('miss', 'Miss.'), ('mrs', 'Mrs.'), ('mr', 'Mr.'), ('dr', 'Dr.'), ('prof', 'Prof.')], default='dr', max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
            ],
            options={
                'verbose_name': 'Applicant Profile',
                'verbose_name_plural': 'Applicants Profile',
            },
            bases=('account.profile',),
        ),
    ]
