# Generated by Django 3.2.3 on 2021-05-20 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joballocation',
            name='job',
            field=models.ForeignKey(help_text='Job id', on_delete=django.db.models.deletion.CASCADE, to='applicant.job'),
        ),
    ]
