# Generated by Django 3.2.3 on 2021-05-22 21:53

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_jobcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name': 'Job Category', 'verbose_name_plural': 'Job Categories'},
        ),
        migrations.AddField(
            model_name='postjob',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applicant.jobcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
