# Generated by Django 3.2.3 on 2021-05-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_auto_20210522_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='is_applied',
            field=models.BooleanField(default=False, help_text='Means Job has been applied', verbose_name='Applied'),
        ),
    ]
