# Generated by Django 3.2.3 on 2021-05-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_postjob_is_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='job',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='job',
            name='sheet',
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='this is description for a job', help_text='job description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postjob',
            name='instructions',
            field=models.TextField(default='these are instructions', help_text='job instruction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postjob',
            name='sample',
            field=models.FileField(default='applicant/sample.pdf', help_text='job sample', upload_to='applicant/%Y/%M'),
        ),
        migrations.AddField(
            model_name='postjob',
            name='sheet',
            field=models.URLField(default='https://docs.google.com/spreadsheets/d/1su0oDIpTORaB-b8cmD5seQ9vgsBgKGNlB1WfeIpJrbk/edit#gid=0', help_text='Job output sheet (google sheet)'),
            preserve_default=False,
        ),
    ]
